service: HuskyFit-API
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

  environment:
    user_pool_id: { Ref: UserPool }
    client_id: { Ref: UserClient }

  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - cognito-idp:AdminInitiateAuth
        - cognito-idp:AdminCreateUser
        - cognito-idp:AdminSetUserPassword
      Resource: "*"

plugins:
  - serverless-offline
  - serverless-add-api-key
  - serverless-plugin-warmup

custom:
  apiKeys:
    - name: noah-api-key

  warmup:
    default:
      enabled: true
      folderName: '.warmup'
      memorySize: 256
      name: warmer-default
      events:
        - schedule: 'cron(0/5 13-5 ? * SUN-SAT *)' # 8:00am to 12:00pm EST | Every 5 minutes | UTX
      package:                                     
        individually: true
        patterns:
          - '!../**'
          - '!../../**'
          - ./**
      timeout: 5
      concurrency: 1

functions:
  getMeals:
    runtime: python3.9
    handler: scraper.lambda_handler
    timeout: 10 # lambda will timeout after 10 secs

    warmup:
      default:
        enabled: true

    events:
      - http:
          path: /{dininghall}/{meal}
          method: get
          private: true

  mockGetMeals:
    runtime: python3.9
    handler: mock.lambda_handler
    timeout: 10 # lambda will timeout after 10 secs

    warmup:
      default:
        enabled: false

    events:
      - http:
          path: /{dininghall}/{meal}/mock
          method: get
          private: true


  # login and signup lambdas
  loginUser:
    handler: auth/login.handler
    events:
      - http:
          path: auth/login
          method: post
          cors: true
          private: true

    warmup:
      default:
        enabled: false

  signupUser:
    handler: auth/signup.handler
    events:
      - http:
          path: auth/signup
          method: post
          cors: true
          private: true

    warmup:
      default:
        enabled: false

  privateAPI:
    handler: auth/private.handler
    events:
      - http:
          path: auth/private
          method: post
          cors: true
          private: true
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn:
              Fn::GetAtt:
                - UserPool
                - Arn
            claims:
              - email
              - name
              - birthdate
    
    warmup:
      default:
        enabled: false

resources:
  Resources:
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: serverless-auth-pool
        Schema:
          - Name: email
            Required: true
            Mutable: true
          - Name: name
            Required: true
            Mutable: true
            AttributeDataType: String
          - Name: birthdate
            Required: true
            Mutable: true
            AttributeDataType: String

        Policies:
          PasswordPolicy:
            MinimumLength: 8
        AutoVerifiedAttributes: ["email"]

    UserClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: user-pool-ui
        GenerateSecret: false
        UserPoolId: { Ref: UserPool }
        AccessTokenValidity: 5
        IdTokenValidity: 5
        ExplicitAuthFlows:
          - "ADMIN_NO_SRP_AUTH"
