Resources:

  WorkoutTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: HuskyFit-Workout
      AttributeDefinitions:
        - AttributeName: UserID
          AttributeType: S
        - AttributeName: Date
          AttributeType: S
      KeySchema:
        - AttributeName: UserID
          KeyType: HASH
        - AttributeName: Date
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5


  FoodLogTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: HuskyFit-Food-Logs
      AttributeDefinitions:
        - AttributeName: UserID
          AttributeType: S
        - AttributeName: Date
          AttributeType: S
      KeySchema:
        - AttributeName: UserID
          KeyType: HASH
        - AttributeName: Date
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  UserInfo:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: HuskyFit-User-Info
      AttributeDefinitions:
        - AttributeName: UserID
          AttributeType: S
      KeySchema:
        - AttributeName: UserID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5


  